version: '3'

services:
  web:
    build:
    # path of dir that contains dockerFiles -> point to the current dir
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
    # path of dir that contains dockerFiles -> point to the current dir
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm", "run", "test"]
